config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #get 'welcome/index'
  # match '(:controller(/:action/(/:id)))', :via => :get
  get 'welcome/awesome' => 'welcome#awesome'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def awesome
    @links = Link.all
    @firstid = Link.first.id
    @lastid = Link.last.id
    @random = rand(@firstid..@lastid)
    @randomlink = Link.find(@random)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeWeb</title>
    <link rel="shortcut icon" type="image/png" href="https://ohshitgit.com/favicon-16x16.png" sizes="16x16"/>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-109763758-3"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-109763758-3');
    </script>
    <%= yield %>
  </body>
</html>

app/views/welcome/awesome.html.erb
<meta charset="UTF-8">
<meta http-equiv="refresh" content="1; url=<%= @randomlink.url %>">
<script type="text/javascript">
  setTimeout(function() { window.location.href = "<%= @randomlink.url %>" }, 5000);
</script>
<title>AwesomeWeb</title>
</head>
<body style="background: white !important;">
  <div class="loading-container">
    <div class="spinner"></div>
    <div class="spinner-center"></div>
    <div class="loading-text">Loading...</div>
  </div>
<!-- Note: don't tell people to `click` the link, just tell them that it is a link. -->
<!-- If you are not redirected automatically, follow this <a href='<%= @randomlink.url %>'>link</a>. -->

app/views/welcome/index.html.erb
<link rel='stylesheet prefetch' href='https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css'>
</head>
<body>
<link rel="stylesheet" href="//brick.a.ssl.fastly.net/Roboto:400"/>
<%= link_to welcome_awesome_path , { :class=>"button", :target=>"_blank" } do %>
    <p>Take me to an Awesome Website!</p>
  <% end %>
</div>
<div class="popup">
    <div class="close ns-close"></div>
    <p class="info">Created by: <a href="https://vedipen.com/" target="_blank">vedipen</a></p>
    <p class="info">Github: <a href="https://github.com/vedipen/awesome-website" target="_blank">awesome-website</a></p>
 </div>
<div class="i">
  <i class="fa fa-info-circle fa-2x" aria-hidden="true"></i>
</div>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.12.1/TweenMax.min.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js'></script>
<script src="https://use.fontawesome.com/76393fa922.js"></script>
<script>
var $button = document.querySelector('.button');
$button.addEventListener("mouseover", function() {
  var duration = 0.3,
      delay = 0.08;
  TweenMax.to($button, duration, {scaleY: 1.6, ease: Expo.easeOut});
  TweenMax.to($button, duration, {scaleX: 1.2, scaleY: 1, ease: Back.easeOut, easeParams: [3], delay: delay});
  TweenMax.to($button, duration * 1.25, {scaleX: 1, scaleY: 1, ease: Back.easeOut, easeParams: [6], delay: delay * 3 });
});

$(document).ready(function() {
  $('.i').click(function(){
    $('.popup').show();
    $('.i').hide();
  });
  $('.close').click(function(){
    $('.popup').hide();
    $('.i').show();
  });
});





</script>